name: m7t
version: '${project.version}'
main: m7t.m7t.M7t
api-version: '1.20'
libraries:
  - "io.javalin:javalin:5.6.3"
  - "org.slf4j:slf4j-simple:2.0.7"
  - "com.fasterxml.jackson.core:jackson-databind:2.13.2"

commands:
   m7t:
      description: Your description
      usage: /m7t remain | add <int time_to_add>